### ISSUE TITLE
[Apply] 申请子域名：zdl.fuckur.mom

### ISSUE THREAD

**Issue by bruce0781** [fuckur-mom/apply#1]
* 您的姓名：Bruce Tian
* 您的聯絡方式：电邮「[bruce@tkong.net](mailto:bruce@tkong.net)」
* 您的專案名稱：zhk智慧考试笔周遭产品发布页
* 您申請的子域類型（NS/CNAME）CNAME
* 傻逼為什麼是傻逼（詳細說明）：https://www.tkong.net/original/breaking-zdlsz.html
* 傻逼的聯絡方式：QQ 818886947

**Comment by AH-dark** [comment]
请指出您的解析域

**Comment by bruce0781** [comment]
202201.ns.pdlnet.work

**Comment by AH-dark** [comment]
已完成解析。
