### ISSUE TITLE
[Apply] Apply for subdomain: xiaolin.fuckur.mom

### ISSUE THREAD

**Issue by bilibilixkz** [fuckur-mom/apply#4]
* 您的姓名：xkz
* 您的联系方式：bilibili_xkz@qq.com
* 您的项目名称：囸厕所云
* 您申请的子域名类型（NS/CNAME）：CNAME
* 傻逼为什么是傻逼（详细说明）：<details>热爱生活 2022/5/16 9:58:12<br />有时候服务器Windows 一直没网 ，没网就是好几天<br /><br />林同学的林 2022/5/16 10:24:55<br />垃圾谷歌DNS的锅<br /><br />林同学的林 2022/5/16 10:25:07<br />不要老是说机器的问题</details>
* 傻逼的联系方式：2326702657

**Comment by AH-dark** [comment]
요청이 통과되었습니다. 해결하려는 대상 도메인을 지정하세요.

**Comment by bilibilixkz** [comment]
> 요청이 통과되었습니다. 해결하려는 대상 도메인을 지정하세요.

CNAME bilibilixkz.github.io

**Comment by AH-dark** [comment]
Parsing added.

![DKOJORJJ{G6ZMXVVNO9TAD5](https://user-images.githubusercontent.com/51253685/169635442-2b54b63d-4c33-49fe-a45a-eb0cbeba7b9e.png)

**Comment by bilibilixkz** [comment]
Please remove the parsing, I don't need it anymore
